version: '3.9'
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: opensea
      POSTGRES_PASSWORD: opensea
      POSTGRES_DB: opensea
    volumes:
      - db_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  backend:
    build: ./backend
    environment:
      PORT: 4000
      DATABASE_URL: postgres://opensea:opensea@db:5432/opensea
      ENCRYPTION_KEY: changemechangemechangemechangeme
    depends_on:
      - db
    ports:
      - "4000:4000"
  frontend:
    build: ./frontend
    depends_on:
      - backend
    ports:
      - "3000:80"
volumes:
  db_data:
